global:
  scrape_interval: 15s # On récupère les données toutes les 15s

scrape_configs:
  # 1. Prometheus s'écoute lui-même
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # 2. cAdvisor (Les métriques Docker : CPU, RAM, Réseau)
  # On utilise le nom du service Docker pour le trouver automatiquement
  - job_name: 'cadvisor'
    dns_sd_configs:
      - names:
        - 'tasks.mon-app_cadvisor'
        type: 'A'
        port: 8080

  # 3. Ton API NestJS (Si tu as activé le module prometheus)
  - job_name: 'api'
    metrics_path: '/metrics'
    dns_sd_configs:
      - names:
        - 'tasks.mon-app_api'
        type: 'A'
        port: 3001