networks:
  monitoring:
    driver: bridge

volumes:
  loki-data-local:
  grafana-data-local:
  prometheus-data-local:

services:
  loki:
    image: grafana/loki:latest
    command: -config.file=/etc/loki/config.yml
    volumes:
      - ./loki.yml:/etc/loki/config.yml
      - loki-data-local:/loki
    ports:
      - "3100:3100"
    networks:
      - monitoring

  promtail:
    image: grafana/promtail:latest
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./promtail-local.yml:/etc/promtail/config.yml
    networks:
      - monitoring
    depends_on:
      - loki

  prometheus:
    image: prom/prometheus:latest
    command: ['--config.file=/etc/prometheus/prometheus.yml']
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data-local:/prometheus
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3030:3000"
    volumes:
      - grafana-data-local:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - monitoring
    depends_on:
      - loki
      - prometheus
