global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    dns_sd_configs:
      - names:
        - 'tasks.mon-app_cadvisor'
        type: 'A'
        port: 8080

  - job_name: 'api'
    metrics_path: '/metrics'
    dns_sd_configs:
      - names:
        - 'tasks.mon-app_api'
        type: 'A'
        port: 3001
