[managers]
manager-1 ansible_host=109.123.247.178 ansible_private_host=109.123.247.178

[workers]
# worker-1 ansible_host=10.0.0.2 ansible_private_host=10.0.0.2

[swarm:children]
managers
workers

[all:vars]
ansible_user=deploy
ansible_ssh_private_key_file=~/.ssh/id_deploy
ansible_python_interpreter=/usr/bin/python3
