{
 "title": "API — Logs",
 "tags": [
  "api",
  "logs",
  "loki"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "replica",
    "label": "Replica",
    "query": "label_values({service=\"mon-app_api\"}, replica)"
   }
  ]
 },
 "panels": [
  {
   "title": "Volume de logs par replica",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (replica) (count_over_time({service=\"mon-app_api\", replica=~\"$replica\"}[$__interval]))",
     "legendFormat": "replica {{replica}}"
    }
   ]
  },
  {
   "title": "Volume par niveau de log",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by (level) (count_over_time({service=\"mon-app_api\", replica=~\"$replica\"} | json [\"$__interval\"]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Logs — tous réplicas",
   "type": "logs",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "{service=\"mon-app_api\", replica=~\"$replica\"} | json"
    }
   ]
  },
  {
   "title": "Erreurs & Warnings",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "{service=\"mon-app_api\", replica=~\"$replica\", level=~\"error|warn|fatal\"}"
    }
   ]
  }
 ]
}