---
- name: Dossier des clés apt
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0750'

- name: Clé GPG Docker
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0640'

- name: Dépôt Docker
  apt_repository:
    repo: >
      deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc]
      https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    filename: docker

- name: Installer Docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: yes

- name: deploy dans le groupe docker
  user:
    name: deploy
    groups: docker
    append: yes

- name: Docker démarré
  systemd:
    name: docker
    enabled: yes
    state: started
